version: '2'
services:
  web:
    # Uncomment to autostart at boottime
    #restart: always
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/log/nginx:/var/log/nginx
      - ./:/var/www/html

  app:
    # Uncomment to autostart at boottime
    #restart: always
    build: docker/php
    depends_on:
      - db
    volumes:
      - ./:/var/www/html

  db:
    # Uncomment to autostart at boottime
    #restart: always
    image: mysql:5.7
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: database
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/log/mysql:/var/log/mysql
